import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('retail_data.csv')
df['month']=pd.DatetimeIndex(df['Date']).month_name()
customers=df.loc[:,['month','Customer_ID']]
totalCust=customers.groupby(['month','Customer_ID']).head(1)
customers['count']=customers.groupby(by='month',sort=False).transform('count')
customers['count']=customers['count'].drop_duplicates()
customers = customers.dropna()
#plt.barh(customers['month'], customers['count'])
#plt.show()

print('*******total customers*********')
print('-------------------------------')
sku=df.loc[:,['month','SKU']]
totalSku=sku.groupby(['month','SKU']).head(1)
skuCount=totalSku.groupby(by='month',sort=False).count()
print('*******total sku_sale*********')
print(skuCount)
print('-------------------------------')
print('*******highest selling sku monthly*********')
hightsel = (df.groupby(['month','SKU'])['SKU'].agg(['count']).sort_values(by='count', ascending=False)
 .reset_index().drop_duplicates('month', keep='first'))
print(hightsel)
print('-------------------------------')
print('*******highest selling SKU_Category monthly*********')
hightCat = (df.groupby(['month','SKU_Category'])['SKU_Category'].agg(['count']).sort_values(by='count', ascending=False)
 .reset_index().drop_duplicates('month', keep='first'))
print(hightCat)
print('-------------------------------')
print('*******total sale amount monthly*********')
sale=df.loc[:,['month','Sales_Amount']]
amt_sale=sale.groupby(['month'],sort=False).sum()
print(amt_sale)
print('----------------------------------')
print('*******total selling Quantity monthly*********')
qty=df.loc[:,['month','Quantity']]
qty_sale=qty.groupby(['month'],sort=False).sum()
print(qty_sale)
print('----------------------------------')
print('*******total selling Amount yearly*********')
print(amt_sale.sum())
print('*******total selling Quantity yearly*********')
print(qty_sale.sum())